### PR TITLE
Convert file to Unix newlines

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Review by lmatiolis — APPROVED** [review]
It was just the `utf-8`, right? LGTM!

**Comment by shepmaster** [comment]
> It was just the utf-8, right? LGTM!

@lmatiolis and the dos -> unix newlines

**Comment by lmatiolis** [comment]
But the only different line is this, right?

`# coding: utf-8`

Or something is missing on the PR?

Thanks!

**Comment by shepmaster** [comment]
> But the only different line is this, right?

I am doing a poor job of communicating, sorry!

image

I changed basically _every_ line, adjusting the newlines from Windows (`\r\n`) to UNIX (`\n`). _Besides whitespace_, the only change should be the `coding` annotation, yes.

**Comment by lmatiolis** [comment]
Ah, that's perfect @shepmaster! Sorry for the confusion! And I was thinking that the github diff was doing a poor job on this one... haha!

Thanks!

**Review by regentgal — APPROVED** [review]
👍

**Review by lmatiolis — APPROVED** [review]

**Pull request merged**
